pipelines:
  workshop-pipeline:
    group: workshops
    materials:
      repo:
        git: https://github.com/faustocv/springboot-workshop-i.git
        branch: master
    stages:
      - Tests:
          jobs:
            unit_tests:
              tasks:
                - exec:
                    command: sh
                    arguments:
                      - c
                      - ./gradle clean test
                      un_tests:
            integration_tests:
              tasks:
                - exec:
                    command: sh
                    arguments:
                      - c
                      - ./gradle clean integrationTest
