pipelines:
  workshop-pipeline:
    group: workshops
    materials:
      repo:
        git: https://github.com/exarcol/springboot-workshop-i.git
        branch: master
    stages:
      - Tests:
          jobs:
            unit_tests:
              tasks:
                - exec:
                    command: sh
                    arguments:
                      - -c
                      - ./gradlew clean test
            integration_tests:
              tasks:
                - exec:
                    command: sh
                    arguments:
                      - -c
                      - ./gradlew clean integrationTest
        - Build:
            jobs: 
              build_fatjar:
                tasks:
                  - exec:
                      command: sh
                      arguments:
                        - -c
                        - ./gradlew jar
